# AppVeyor CI configuration:

# We don't do a shallow clone of just the source archive as we want to get
# the diff for source file checks.
# We do limit to the last few commits to speed things up:
clone_depth: 10

# Don't run on pushes to feature branches: pull requests cover those.
branches:
  only:
    - master

platform: x64

environment:
  matrix:
    - GENERATOR: Visual Studio 12
      CONFIG: Debug

    - GENERATOR: Visual Studio 12
      CONFIG: Release

    - GENERATOR: Visual Studio 12 Win64
      CONFIG: Debug

    - GENERATOR: Visual Studio 12 Win64
      CONFIG: Release

before_build:
  - call "c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
  - cd c:\projects\drltrace
  - git submodule update --init --recursive
  - mkdir build
  - cd build

build:
  parallel: true  

build_script:
  #parallel: true
  - cmake "-G%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIG% ..\drltrace_src\
  - cmake --build . --config "%CONFIG%"

test_script:
  - ctest -VV -C "%CONFIG%"