language:
  - c
  - cpp

os: linux
compiler: gcc  
 
dist: trusty

env:
  - BUILD=x86_64-linux-gnu
    CXXFLAGS=-m64 CFLAGS=-m64 LDFLAGS=-m64
  - BUILD=i686-linux-gnu
    CXXFLAGS=-m32 CFLAGS=-m32
      
before_script:
  - "mkdir build"
  - "cd build"
  - "cmake -DBUILD_TOOL_TESTS ../drltrace_src/"

script: 
  - "make"
  - "ctest -VV"