language:
  - c
  - cpp

  
os: linux
compiler: gcc  

sudo: required 
dist: trusty

env:
  - BUILD=x86_64-linux-gnu
    CXXFLAGS=-m64 CFLAGS=-m64 LDFLAGS=-m64
  - BUILD=i686-linux-gnu
    CXXFLAGS=-m32 CFLAGS=-m32

install:
   - sudo apt-get install gcc-multilib g++-multilib
    
before_script:
  - "mkdir build"
  - "cd build"
  - "cmake -DBUILD_TOOL_TESTS=ON ../drltrace_src/"

script: 
  - "make"
  - "ctest -VV"